apiVersion: v1
kind: Service
metadata:
  name: iot-mqtt
spec:
  clusterIP: None # Headless service
  selector:
    app: iot-device
  ports:
    - port: 5000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-mqtt
spec:
  replicas: 10
  selector:
    matchLabels:
      app: iot-device
  template:
    metadata:
      labels:
        app: iot-device
    spec:
      containers:
      - name: mqtt-device
        image: ${DOCKERHUB_USERNAME}/iot-mqtt:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SIM_LATENCY
          value: "0.5"
        - name: SIM_LOSS
          value: "0.1"
        - name: FAIL_PROB
          value: "0.05"
        - name: FAIL_DUR
          value: "40"
        ports:
        - containerPort: 5000
        command: ["python", "mqtt_device.py"]
